package com.example.wschat.ultil

object Constans {
   const val tokenSocket = "v2.public.eyJkZXYiOiIwOTAxMDkxNDA3Iiwic3ViIjoiMTkyMTE4MjYzNzE3NTYwMzIwIiwiaXNzIjoibWVzc2VuZ2VyIiwiaWF0IjoiMjAyMS0wNi0xNVQwMTowNDoyNi44NzlaIiwiZXhwIjoiMjAyMi0wNi0xNVQwMTowNDoyNi44NzlaIn2k6TzQl4NhvvTkVcGwFQ5gg6h3bB_czbbcSPio9R9q_XvbieFoKHDm6muXEuT2Vah17gAY6sgRVvGcXleOuAQF"
    const val identify = "identify"

}